# -*- coding: utf-8 -*-
"""mzi4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Lncc0il1fsmQVuLNqoD9iOX5LUUzpsMP
"""

import sympy as sp

p = sp.randprime(70000, 2**64)
p

import random

g = 1

while not sp.is_primitive_root(g, p):
  g = random.randint(2, p)

g, sp.is_primitive_root(g, p)

x = random.randint(2, p - 2)
x

y = pow(g, x, p)
y

pubkey = (y, p, g)
privkey = (x, p)

import itertools

message = 'Hello world! This is not RSA :)'

encrypted = [
             (pow(g, k, p), m * pow(y, k, p) % p)
             for m, k
             in zip(
                 message.encode('utf-8'),
                 itertools.starmap(random.randint, itertools.repeat((2, k - 2))),
             )
]
encrypted

decrypted = bytes(b * pow(a, p - 1 - x, p) % p for a, b in encrypted).decode('utf-8')
decrypted