# -*- coding: utf-8 -*-
"""mzi5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OYgklQR8rEw4ITZG5Lgj5Xg0xoNMn2Gn
"""

import hashlib

def hmac(key, message, hashtype):
  hashfunc = hashtype()
  outputsize = hashfunc.digest_size
  blocksize = hashfunc.block_size

  if len(key) > blocksize:
    key = hashtype(key).digest()

  key.ljust(blocksize, b'\0')

  okeypad = bytes(k ^ 0x5c for k in key)
  ikeypad = bytes(k ^ 0x36 for k in key)

  return hashtype(okeypad + hashtype(ikeypad + message).digest()).digest()

key = b'key'
message = b'Hello world!'
hashtype = hashlib.sha1
hashfunc = hashtype()
outputsize = hashfunc.digest_size
blocksize = hashfunc.block_size

outputsize, blocksize

if len(key) > blocksize:
  key = hashtype(key).digest()

key.ljust(blocksize, b'\0')

key

okeypad = bytes(k ^ 0x5c for k in key)
ikeypad = bytes(k ^ 0x36 for k in key)

okeypad, ikeypad

hmachash = hashtype(okeypad + hashtype(ikeypad + message).digest()).digest()

hmachash, hmachash.hex()

hmachash == hmac(key, message, hashlib.sha1)